class task_name():
    
    update_birthday = "دریافت مشتریان برای پیامک تبریک تولد"
    set_order_point = "ذخیره نمودن نقطه سفارش"
    get_report_from_hesabro_link = "get_report_from_hesabro_link"
    get_coin_report_from_hesabro_link = "دریافت سکه های مشتریان از گزارشات با استفاده از لینک"
    run_honeymoonatr = "سایت هانی مون عطر قدیم"
    salary = "حقوق"
    update_birthday_call_brs = "دریافت مشخصات مشتریان برای تماس شعب"
    send_birthday_data_to_sheets = "ارسال تولدی ها در گوگل شیت"
    active_in_site = "فعال نمودن محصولات در سایت مای هانی مون"
    # modification_barcodes = "اصلاح قیمت بارکدهای بدون قیمت"
    correct_zero_prices_barcodes = "اصلاح قیمت بارکدهای بدون قیمت"
    obsolete = "متروک یا غیر متروک نمودن محصولات"
    Update_hesabro_customers_from_hamyar =  "بروزرسانی مشتریان حسابرو از فایل همیار"
    def __init__(self):
        self.update_birthday = "دریافت مشتریان برای پیامک تبریک تولد"
        self.set_order_point =  "ذخیره نمودن نقطه سفارش"
        self.get_report_from_hesabro_link = "get_report_from_hesabro_link"
        self.get_coin_report_from_hesabro_link = "دریافت سکه های مشتریان از گزارشات با استفاده از لینک"
        self.run_honeymoonatr = "سایت هانی مون عطر قدیم"
        self.salary = "حقوق"
        self.update_birthday_call_brs = "دریافت مشخصات مشتریان برای تماس شعب"
        self.send_birthday_data_to_sheets = "ارسال تولدی ها در گوگل شیت"
        self.active_in_site = "فعال نمودن محصولات در سایت مای هانی مون"
        # self.modification_barcodes = "اصلاح قیمت بارکدهای بدون قیمت"
        self.correct_zero_prices_barcodes = "اصلاح قیمت بارکدهای بدون قیمت"
        self.obsolete = "متروک یا غیر متروک نمودن محصولات"
        self.Update_hesabro_customers_from_hamyar = "بروزرسانی مشتریان حسابرو از فایل همیار"